[tool.poetry]
name = "oz-fastapi"
version = "0.1.0"
description = ""
authors = ["jwhjkl0720-alt <jwhjkl0720@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
